# Generated by Django 5.2.3 on 2025-07-04 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message",
            new_name="request",
        ),
        migrations.AlterField(
            model_name="message",
            name="category",
            field=models.CharField(choices=[("notes", "Notes"), ("reminders", "Reminders")]),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="responses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
