# Generated by Django 5.2.3 on 2025-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_request_parent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='parent_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
