# Generated by Django 5.2.3 on 2025-07-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_rename_message_message_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="category",
            field=models.CharField(blank=True, choices=[("notes", "Notes"), ("reminders", "Reminders")], null=True),
        ),
    ]
