# Generated by Django 5.2.3 on 2025-06-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_request_parent_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
